version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8001:8001"
    env_file: .env